# Generated by Django 2.1.1 on 2018-10-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type_of_Message', models.CharField(max_length=2)),
                ('IMEI', models.CharField(max_length=256)),
                ('data', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('lat', models.CharField(max_length=256)),
                ('lot', models.CharField(max_length=256)),
                ('speed', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('height', models.CharField(max_length=256)),
                ('sats', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
