# Generated by Django 2.1.1 on 2018-10-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20181016_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incoming_data',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Incoming Data'},
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='IMEI',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='Type_of_Message',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='course',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='data',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='height',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='lat',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='lot',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='sats',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='speed',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='incoming_data',
            name='time',
            field=models.CharField(default='NA', max_length=256),
        ),
    ]
