# Generated by Django 2.1.1 on 2018-10-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20181017_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming_data',
            name='Type_of_Message',
            field=models.CharField(default='NA', max_length=3),
        ),
    ]
