# Generated by Django 2.1.1 on 2018-10-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20181022_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming_data',
            name='id2',
            field=models.CharField(default='NA', max_length=4),
        ),
    ]
