# Generated by Django 2.1.1 on 2018-10-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_incoming_data_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming_data',
            name='id2',
        ),
    ]
