# Generated by Django 2.1.1 on 2018-10-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_remove_incoming_data_id2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IMEI', models.CharField(max_length=20, unique=True)),
                ('Gos_Nomer', models.CharField(max_length=7)),
                ('Description', models.CharField(default='NA', max_length=156)),
            ],
        ),
    ]
