# Generated by Django 2.1.1 on 2018-10-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming_data',
            name='server_date_time',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
